---
title: "Mendoza et al. 2019 and AGORA2 figures"
output: html_document
date: '2024-05-16'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
theme_set(theme_bw())
```

```{r}
mendoza_data <- read_csv("figure_data/fig_mendoza.csv", show_col_types = F) %>%
  mutate(organism = case_when(
    grepl("BPE", model) | (model == "iBP1870.xml") ~ "Bordetella pertussis",
    grepl("LPL", model) ~ "Lactobacillus plantarum",
    grepl("PPU", model) | (model == "iJP962.xml") ~ "Pseudomonas putida"
  )) %>%
  mutate(method = case_when(
    grepl("_AU", model) ~ "AuReMe",
    grepl("_CA", model) ~ "CarveMe",
    grepl("_ME", model) ~ "Merlin",
    grepl("_MD", model) ~ "MetaDraft",
    grepl("_MS", model) ~ "ModelSEED",
    grepl("_PT", model) ~ "Pathway Tools",
    grepl("_RA", model) ~ "RAVEN",
    TRUE ~ "Manual"
  )) %>%
  mutate(dupe_prop = duplicates/all_rxns) %>%
  mutate(dead_prop = `dead-ends`/all_rxns) %>%
  mutate(dil_prop = `dilution-blocked`/all_rxns) %>%
  mutate(loop_prop = loops/all_rxns) %>%
  select(
    -model, -duplicates, -`dead-ends`, -`dilution-blocked`, -loops, -all_rxns
  ) %>%
  pivot_longer(
    c(dupe_prop, dead_prop, dil_prop, loop_prop),
    names_to = "test",
    values_to = "prop"
  ) %>%
  mutate(test = case_when(
    test == "dupe_prop" ~ "Duplicate Test",
    test == "dead_prop" ~ "Dead-End Test",
    test == "dil_prop" ~ "Dilution Test",
    test == "loop_prop" ~ "Loop Test"
  ))
```

```{r}
mendoza_data %>%
  ggplot(aes(x = organism, y = prop, fill = test)) +
    geom_violin() +
    labs(
      x = "Organism",
      y = "Proportion of Reactions Flagged by Test",
      fill = ""
    )
```

```{r}
mendoza_data %>%
  mutate(method = relevel(factor(method), "Manual")) %>%
  ggplot(aes(x = method, y = prop, fill = test)) +
    geom_violin(show.legend = FALSE) +
    facet_wrap(. ~ test) +
    labs(
      x = "Reconstruction Method",
      y = "Proportion of Reactions Flagged By Test"
    ) +
    theme(
      strip.background = element_blank(),
      panel.grid = element_blank(),
      axis.text.x = element_text(angle = 45, hjust = 1)
    )
```


```{r}
agora_data <- read_csv("figure_data/fig_agora.csv", show_col_types = F)
```

